---
title: "R Notebook"
output: html_notebook
---
```{r}
library(OnlineImages)
```

Make an error estimate that depends on the standard deviation of the distribution.
```{r}
relerr <- function(a, b, median, sigma) {
  abs((b - a) / sigma)
}
```


```{r}
i <- 10
j <- 20
N <- 1000L
avg <- 3.7
stdev <- 1.0
base <- build_tierney(c(i, j), N)
ci_cnt <- dim(base$buf)[1]
all <- array(0, dim = c(i, j, N))

means <- ((1:N) * 19937) %% 20
for (ci_idx in 1:N) {
  img <- array(rnorm(i*j, mean = means), dim = c(i, j))
  base <- quantile_add(base, img)
  all[,,ci_idx] <- img
}
stopifnot(base$n == N)
q <- quantiles(base)
reord_all <- aperm(all, c(3, 1, 2))
```


```{r}
errval <- array(0, dim = c(3, i, j))
for (jr in 1:j) {
  for (ir in 1:i) {
    qq <- unname(quantile(reord_all[,ir, jr], probs = c(0.025, 0.5, 0.975)))
    
    low <- 
    errval[1, ir, jr] <- q$lower[ir, jr] - qq[1]
    errval[2, ir, jr] <- q$median[ir, jr] - qq[2]
    errval[3, ir, jr] <- q$upper[ir, jr] - qq[3]
  }
}
errhist <- aperm(errval, c(2, 3, 1))
```

```{r}
hist(errhist[,,1], main = "Error in Lower CI")
```


```{r}
hist(errhist[,,2], main = "Error in Median")
```


```{r}
hist(errhist[,,3], main = "Error in Upper CI")
```

