# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

quantile_add <- function(base, image) {
    .Call(`_OnlineImages_quantile_add`, base, image)
}

sample_matrix <- function(deep) {
    .Call(`_OnlineImages_sample_matrix`, deep)
}

iter_matrix <- function(deep) {
    .Call(`_OnlineImages_iter_matrix`, deep)
}

