# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Add an image to the stack from which to compute quantiles.
#'
#' @param base The object that `build_tierney` made.
#' @param image A two-dimensional array of numeric. Can include NaN values.
#' @return A modified base object, that you pass in the next time.
#'
quantile_add <- function(base, image) {
    .Call(`_OnlineImages_quantile_add`, base, image)
}

